### Teste de Registro
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "name": "Usuario Teste",
  "login": "teste_trabalho@email.com",
  "telephone": "11988887777",
  "birthDate": "1995-05-20",
  "password": "senha123",
  "role": "ADMIN"
}